#!/bin/sh

cd $(git rev-parse --show-toplevel)
CONFLICTS=$(git diff --name-only --diff-filter=U)
if [[ "$CONFLICTS" != "" ]]; then
  ${EDITOR:-vim} -p $CONFLICTS
else
  echo "No conflicts to fix..."
fi
